//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Addresses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int ReclD { get; set; }
        public int ID { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual Entry Entry { get; set; }
    }
}
